#!/bin/bash

# Docker Quick Reference Script
# Use this for quick command lookups

echo "🐳 Docker Quick Reference"
echo "========================="
echo ""
echo "BUILD:"
echo "  docker build -t name ."
echo "  docker build -t name:tag ."
echo ""
echo "RUN:"
echo "  docker run name"
echo "  docker run -d -p 8080:80 name        # detached with port"
echo "  docker run -it name bash             # interactive"
echo "  docker run -v \$(pwd):/app name       # with volume"
echo ""
echo "MANAGE:"
echo "  docker ps                            # list running"
echo "  docker ps -a                         # list all"
echo "  docker stop <id>                     # stop container"
echo "  docker rm <id>                       # remove container"
echo "  docker logs <id>                     # view logs"
echo "  docker exec -it <id> bash            # enter container"
echo ""
echo "IMAGES:"
echo "  docker images                        # list images"
echo "  docker rmi <id>                      # remove image"
echo "  docker pull image:tag                # pull from hub"
echo ""
echo "COMPOSE:"
echo "  docker compose up                    # start services"
echo "  docker compose up -d                 # start detached"
echo "  docker compose down                  # stop services"
echo "  docker compose logs                  # view logs"
echo ""
echo "CLEANUP:"
echo "  docker system prune                  # remove unused"
echo "  docker system prune -a               # remove all unused"
echo ""
